# ZTM (Zero-Trust Monitoring) Configuration
# Last Updated: 2025-05-28

# Core Settings
core:
  enabled: true
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  audit_log: "logs/ztm_audit.log"
  max_log_size_mb: 100
  max_log_backups: 5

# Security Policies
policies:
  # Access Control Policies
  access_control:
    enforce_least_privilege: true
    require_mfa: true
    session_timeout_minutes: 30
    
  # Data Protection Policies
  data_protection:
    encrypt_sensitive_data: true
    encryption_algorithm: "AES-256-GCM"
    key_rotation_days: 30
    
  # Monitoring Policies
  monitoring:
    enable_realtime_monitoring: true
    enable_behavioral_analytics: true
    anomaly_detection_threshold: 0.85  # 0.0 to 1.0

# Module Monitoring
modules:
  # Critical Modules (High Priority)
  critical:
    - "miso.math.t_mathematics"
    - "miso.simulation.prism"
    - "vxor.vision"
    - "miso.logic.q_logik"
    
  # Standard Modules (Medium Priority)
  standard:
    - "miso.core"
    - "vxor.control"
    - "vxor.gestalt"
    
  # External Integrations (Low Priority)
  external:
    - "vxor.quantum"
    - "vxor.chronos"

# Alerting Configuration
alerting:
  enabled: true
  providers:
    - type: "console"
      level: "WARNING"
    - type: "file"
      level: "INFO"
      path: "logs/ztm_alerts.log"
    - type: "email"
      level: "ERROR"
      smtp_server: "smtp.example.com"
      smtp_port: 587
      username: "info@mimitechai.com"
      password: "${SMTP_PASSWORD}"  # Use environment variable
      recipients:
        - "info@mimitechai.com"
        - "info@mimitechai.com"

# Performance Settings
performance:
  max_threads: 8
  queue_size: 1000
  batch_size: 100
  flush_interval_seconds: 5

# Integration Settings
integrations:
  void_protocol:
    enabled: true
    config_path: "../void/config/void_context.yaml"
    verify_interval_seconds: 60
    
  # Add other integrations as needed
  prometheus:
    enabled: false
    port: 9090
    
# Custom Rules
custom_rules:
  - name: "sensitive_data_access"
    description: "Monitor access to sensitive data"
    severity: "HIGH"
    condition: "operation_type in ['READ_SENSITIVE', 'WRITE_SENSITIVE']"
    action: "ALERT"
    
  - name: "unusual_activity"
    description: "Detect unusual activity patterns"
    severity: "MEDIUM"
    condition: "anomaly_score > 0.9"
    action: "REVIEW"

# Whitelist (Always allow these)
whitelist:
  ip_addresses:
    - "127.0.0.1"
    - "::1"
  
  # Add trusted service accounts
  service_accounts:
    - "system"
    - "ztm-service"

# Blacklist (Always block these)
blacklist:
  # Add known malicious IPs or accounts
  ip_addresses: []
  accounts: []

# Auto-remediation Actions
auto_remediation:
  enabled: true
  actions:
    - name: "temporary_block"
      condition: "failed_attempts > 5"
      action: "block_ip_for_minutes(30)"
      
    - name: "disable_account"
      condition: "is_compromised == true"
      action: "disable_account()"
      
    - name: "notify_admin"
      condition: "severity == 'CRITICAL'"
      action: "send_alert('CRITICAL_ALERT')"
