# VXOR AI Blackbox - Standardkonfiguration
# Diese Datei enthält die Standardeinstellungen für alle VXOR AI Blackbox-Sicherheitskomponenten

# Allgemeine Sicherheitseinstellungen
security:
  encryption:
    aes_key_size: 32            # 256 Bit
    iv_size: 12                 # 96 Bit (für GCM)
    tag_size: 16                # 128 Bit Auth-Tag
    key_derivation_iterations: 600000
  
  quantum_resistant:
    kyber_variant: "512"        # Kyber Variante (512, 768, 1024)
    dilithium_variant: "2"      # Dilithium Variante (2, 3, 5)
    ntru_variant: "HRSS"        # NTRU Variante
  
  key_management:
    key_store_dir: "~/.vxor/keystore"
    rotation_periods:
      kyber: 30                 # Tage
      ntru: 60                  # Tage
      dilithium: 90             # Tage
      aes: 7                    # Tage
    retention:
      keep_old_keys: true       # Behalte alte, rotierte Schlüssel
      archive_after_days: 30    # Archiviere Schlüssel nach 30 Tagen Inaktivität
  
  logging:
    log_dir: "~/.vxor/logs"
    default_level: "INFO"
    secure_logging: true        # Protokolliert keine sensitiven Daten
    log_rotation:
      max_size_mb: 10
      backup_count: 5

# T-Mathematics Engine Sicherheitseinstellungen
t_mathematics:
  mlx_tensor:
    use_apple_neural_engine: true    # Nutze die Apple Neural Engine des M4 Max
    optimize_for_mlx: true           # MLX-spezifische Optimierungen
    secure_memory: true              # Spezieller Speicherschutz für MLX
  
  torch_tensor:
    use_mps: true                    # Verwende Metal Performance Shaders für GPU
    optimize_for_metal: true         # Metal-spezifische Optimierungen
    secure_memory: true              # Spezieller Speicherschutz für PyTorch

# M-LINGUA Sicherheitseinstellungen
m_lingua:
  secure_parsing: true               # Sichere Eingabevalidierung
  backend_selection: "auto"          # Automatische Backend-Auswahl (mlx, torch, numpy)
  tensor_operations:
    validate_operations: true        # Validiere Operationen vor Ausführung
    sandbox_execution: true          # Führe Operationen in Sandbox aus
  
  security_level: "high"             # Sicherheitsstufe (low, medium, high)

# Obfuskation und Code-Schutz
obfuscation:
  pyarmor:
    enabled: true
    obf_code: 2                      # Obfuskationsstufe (0-2)
    obf_mod: 2                       # Modulobfuskation (0-2)
    wrap_mode: 1                     # C-Wrapping (0-1)
    restrict_mode: 3                 # Einschränkungsstufe (0-4)
  
  nuitka:
    enabled: true
    standalone: true                 # Erstelle eigenständige Binaries
    remove_output: true              # Entferne Build-Ausgaben
    jobs: 4                          # Anzahl paralleler Build-Jobs
    lto: "yes"                       # Link Time Optimization
  
  llvm:
    control_flow_flattening: true
    bogus_control_flow: true
    string_encryption: true
    function_splitting: true
    opaque_predicates: true

# Laufzeitschutz
runtime_protection:
  veracrypt:
    enabled: true
    volume_type: "normal"            # normal oder hidden
    encryption: "aes-twofish-serpent"
    hash_algorithm: "sha-512"
    filesystem: "exfat"
  
  ram_vault:
    enabled: true
    size_mb: 512                     # Größe des In-Memory-Volumes
    encryption: "aes-256-ctr"
    swap_protection: true
  
  anti_debug:
    enabled: true
    detect_ptrace: true
    detect_virtualization: true
    detect_hooks: true
    detect_memory_analysis: true
    response: "shutdown"             # shutdown, wipe_keys, alert

# Secure Boot
secure_boot:
  authentication:
    methods:
      passphrase: true
      hardware_token: false          # Erfordert YubiKey oder ähnliches
      biometric: false               # Erfordert Biometrische Authentifizierung
    required_methods: 1              # Anzahl der erforderlichen Methoden
  
  integrity:
    check_binaries: true
    check_libraries: true
    check_config: true
    digital_signature: true
  
  lockout_policy:
    max_attempts: 5
    lockout_duration_minutes: 30

# Sichere Updates
secure_updates:
  signature_verification:
    algorithms: ["dilithium2"]
    required_signatures: 1
    crl_check: true
  
  update_package:
    format: "vxor_package"
    encryption: "aes-256-gcm"
    compression: "zstd"
  
  deployment:
    atomic: true                    # Alles-oder-nichts Updates
    rollback: true                  # Automatisches Rollback bei Fehler
    testing: "pre_deployment"       # Automatische Tests vor Aktivierung
