transfer_baseline:
  version: v2.1
  tag: v2.0-transfer-baseline
  quantum_feature_dimensions: 10  # Zurück zu bewährtem Wert
  hybrid_balance: 0.68            # Mehr klassische Stabilität
  risk_adjustment: 0.25           # Konservativere Entscheidungen
  confidence_mode: dynamic
  regime_adaptation: true
  entanglement_depth: 4
  uncertainty_threshold: 0.015  # Reduziert für höhere Confidence
  volatility_scaling_factor: 0.15
  target_metrics:
    sharpe_ratio_min: 1.5
    accuracy_min: 0.85
    transfer_effectiveness_min: 0.8
    max_latency_ms: 50
    max_drawdown: 0.15
    min_confidence: 0.85
vx_psi:
  optimization_enabled: true
  parameter_adaptation: true
  confidence_monitoring: true
vx_nexus:
  resource_allocation: optimized
  load_balancing: true
  performance_monitoring: true
vx_control:
  auto_fallback: true
  threshold_monitoring: true
  alert_system: true
market_regime_detection:
  enabled: true
  regimes:
  - stable
  - trending
  - volatile
  adaptation_rules:
    stable:
      hybrid_balance_modifier: 0.05
      confidence_threshold_modifier: -0.05
      risk_factor_modifier: -0.02
    trending:
      hybrid_balance_modifier: 0.0
      confidence_threshold_modifier: 0.0
      risk_factor_modifier: 0.0
    volatile:
      hybrid_balance_modifier: -0.05
      confidence_threshold_modifier: 0.1
      risk_factor_modifier: 0.05
monitoring:
  enabled: true
  check_interval_seconds: 30
  alert_thresholds:
    sharpe_ratio_drop_percent: 10
    accuracy_drop_percent: 5
    confidence_min: 0.85
    latency_max_ms: 60
    drawdown_increase_percent: 5
  rollback_triggers:
    sharpe_ratio_drop_percent: 15
    accuracy_drop_percent: 8
    confidence_min: 0.8
    consecutive_failures: 5
canary:
  enabled: true
  traffic_percentage: 10
  duration_minutes: 30
  success_criteria:
    sharpe_ratio_min: 1.45  # Weniger streng für Stabilität
    accuracy_min: 0.85     # Weniger streng für Stabilität
    confidence_min: 0.82   # Weniger streng für Stabilität
  rollout_stages:
  - traffic_percent: 10
    duration_minutes: 30
  - traffic_percent: 25
    duration_minutes: 60
  - traffic_percent: 50
    duration_minutes: 120
  - traffic_percent: 100
    duration_minutes: -1
fallback:
  enabled: true
  previous_baseline: v1.0-transfer-baseline
  fallback_parameters:
    quantum_feature_dimensions: 10
    hybrid_balance: 0.7
    risk_adjustment: 0.15
    confidence_mode: static
    regime_adaptation: false
  auto_recovery:
    enabled: true
    recovery_attempts: 3
    recovery_delay_minutes: 5
logging:
  level: INFO
  file: production_transfer_baseline_v2.0.log
  rotation: daily
  retention_days: 30
  snapshots:
    enabled: true
    interval_minutes: 15
    directory: agi_missions/production_snapshots/
    format: json
    compression: true
security:
  void_protocol: true
  ztm_monitoring: true
  audit_logging: true
deployment:
  version: v2.1
  deployed_by: VXOR-AGI-System
  deployment_date: '2025-08-03T04:20:03.491821'
  validation_status: A/B-Test-Validated
  statistical_significance: p < 0.0001
  effect_sizes: Very Large Effects (Cohen's d > 0.8)
  approval_status: APPROVED
  fine_tuning_applied: true
  canary_feedback_integrated: true
